# Copyright (c) 2026, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---

# run this only for valkey_master and valkey_replica device group
- name: Run Valkey Certification Tasks
  hosts: valkey_master:valkey_replica
  gather_facts: true
  become: true
  tasks:
    - name: Certify Valkey Installation  # noqa run-once
      ansible.builtin.import_role:
        name: itential.valkey.valkey
        tasks_from: certify-valkey

# run this only for valkey_sentinel device group
- name: Run Sentinel Certification Tasks
  hosts: valkey_sentinel
  gather_facts: true
  become: true
  tasks:
    - name: Certify Sentinel Installation  # noqa run-once
      ansible.builtin.import_role:
        name: itential.valkey.valkey
        tasks_from: certify-sentinel
